### ISSUE TITLE
Dev implements todo list persistence

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#145]
- [x] Dev implements serialization to text file
- [x] Dev implements deserialization from text file
- [x] Dev implements auto-save upon app quit
- [x] Dev implements auto-load upon app start

**Comment by avidrucker** [comment]
Marking manually closed. This can be polished and optimized further, as needed, later.
