### ISSUE TITLE
Project maintainer oversees rewrite of README to be super user friendly

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#221]
- [x] Researcher conducts a 15 min session to better understand best writing practices for READMEs
- [x] Writer redrafts the current README to better organize the information contained within & identify alternative layouts, document architecture
- [x] Write expands main readme into 5: 
    - [x] main readme
    - [x] dev readme
    - [x] designer readme
    - [x] writer readme
    - [x] general contributor readme

**Comment by avidrucker** [comment]
Research is complete! Source: https://bulldogjob.com/news/449-how-to-write-a-good-readme-for-your-github-project

Moving on to the rewrite phase. Here are some components ideally to include:
- [ ] Titles and internal titles
- [ ] Intro (the project's aim)
- [ ] Technologies
- [ ] How to Run
- [ ] Table of contents
- [ ] Illustrations
- [ ] Scope of functionalities 
- [ ] Examples of use
- [ ] Project status 
- [ ] Sources
- [ ] Other information

**Comment by avidrucker** [comment]
This appears to need more time. Also, best to split up these multi-person tasks into separate issues.

**Comment by avidrucker** [comment]
Manually marking as closed in connection with pull request #222 and subsequent minor fixes #223, #225, and #226
