### ISSUE TITLE
Project maintainer further enhances README

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#228]
Re-issuing as a continuation of #221 to complete the bottom 6 check list items

- [x] ~~Titles and internal titles~~
- [x] ~~Intro (the project's aim)~~
- [x] ~~Technologies~~
- [x] ~~How to Run~~
- [x] ~~Table of contents~~
- [x] Illustrations
- [ ]  Scope of functionalities
- [ ] Examples of use
- [ ] Project status
- [x] Sources
- [ ]  Other information

- [x] Writer increases the ease of reading the project description with readability utilities
