### ISSUE TITLE
Dev writes test cases for conductReviews

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#282]
- [ ] Dev writes test for function run prevention guard occurring correctly for 2nd to last item being marked
- [ ] Dev writes test for function run prevention guard occurring correctly for 2nd to last item being completed
- [ ] Dev writes test to confirm conduct reviews function can handle mid-list items being completed (non-markable)
