### ISSUE TITLE
Dev creates JavaScript DOM manip test

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#303]
as a front-end test with no styling, prior to using a framework

User Stories
- [x] User sees upon load AFFVP title heading
- [x] User sees upon load an input text box to enter new todo items
- [x] User sees upon load a button with which to submit new todo items
- [x] User can enter text into input box & press "Create New Todo" to add a new todo to their list of todos
- [x] User sees the input box get reset back to default after pressing the "Create New Todo" button
- [x] User sees nothing happen when they click on the "Create New Todo" if there is no text in the input box

**Comment by avidrucker** [comment]
Closing manually in connection with pull request issue, plus adding extra time for worthwhile value #310
