### ISSUE TITLE
Architect cleans up repo structure

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#356]
- [ ] Dev nests test folders under one `test` folder
- [ ] Dev removes NYC code coverage reports folder until TypeScript codecov feature is implemented (awaiting issue link)
- [ ] Dev modifies build command which exports TSC generated JavaScript files to `dist` folder
