### ISSUE TITLE
Dev improves prototype based on feedback from in-person demo

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#385]
The current prototype jumps from "import new screen 002" to "home screen (unmarked) 004" where there are multiple inbetween state changes and screen updates that would occur (for adding each todo.
- [x] Dev makes inbetween screens for 002 and 004

Additionally, screen # 005 should appear twice, to ask regarding both items B and C (currently it just asks regarding item B).
- [x] Dev adds 2nd screen 005 to ask regarding item C

Focus screen 007 is incorrect - it should not show item A, it should show item C (because item C was the CMWTD).
- [x] Dev fixes incorrect screen 007 display

Lastly, to show the updates in state change all the way through the entire prototype demo, the screen labels should be updated once per each state change. Perhaps letters can be used to show each state change, so screens can stay numbered as-is to refer to screen designs.
- [x] Dev adds letters to screen labels to show prototype demo "steps"

**Comment by avidrucker** [comment]
Marking as closed in connection with pull request issue over here: https://github.com/avidrucker/autofocus-ui/pull/3
