### ISSUE TITLE
Architect creates an NPM package for autofocus core

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#400]
which will become a dependency for the desktop electron app

- [x] Architect consumes NPM distro setup learning materials
- [ ] Architect creates NPM package of `autofocus-core` (currently named `autofocus-exp`)
- [ ] Architect creates NPM package of `autofocus-ui`
- [ ] Architect adds `autofocus-core` and `autofocus-ui` as dependencies to desktop electron app at `autofocus-app`

Setup learning materials link: https://medium.com/the-andela-way/build-and-publish-your-first-npm-package-a4daf0e2431

**Comment by avidrucker** [comment]
I was able to successfully publish the core library today, which uses https://github.com/avidrucker/fp-autofocus/ as the domain logic code, rather than this repository.

While I have been able to successfully publish a components-only library (autofocus-ui), it is not yet mature enough to use as-is. Therefore, I've decided to create a new repo "autofocus-pwa" which relies on for now only the core domain logic from fp-autofocus. Once the components have matured enough to be exported and used as-is, I may republish them for re-use elsewhere.
