### ISSUE TITLE
Dev builds app flow, screens in React app

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#436]
This is a pretty big epic task comprising of a number of issues that need to be clearly defined and then resolved:
- [ ] Basic app screen/state transition is built out for React MVP app
    - [ ] Dev builds home screen
        - [ ] Dev builds welcome / clean home state
        - [ ] Dev builds home screen (with list items)
    - [ ] Dev builds review screen
    - [ ] Dev builds focus screen

Each of these would suggest user stories such as:
- [ ] "User sees welcome screen upon loading the app for the first time OR when there are no to-do items in their list"
- [ ] "User can, when there are to-do items that can be reviewed, go into review mode where they see the review screen and can prioritize one task over another"
- [ ] "User can quit a review session before it has been completed and items marked/prioritized during the review session remain marked/prioritized"
