### ISSUE TITLE
Project manager invites new collaborators

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#76]
- [ ] (15 min) break this issue down into smaller issues
- [ ] (30 min) review repo best practices by Yegor
- [ ] (30 min) research more broadly best practices for making projects easy to contribute to
  -  [ ] read [this article](https://help.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests)
- [ ] (30 min) consult 3 people in the industry for tips, advice, suggestions on how best to support/acknowledge contributors
- [ ] (30 min) consolidate best practices feedback & research into `repo_contribution_research.md`

**Comment by avidrucker** [comment]
As of today, 3 people have been invited to inspect repo.
